Theme categorization update
navikt/crm-journal-utilities pull request #95
Opened 2024-03-11 07:44 UTC by saramoh2309

Updated design for themeCategorization cmp

2024-04-02 07:27 UTC, mamikals requested changes
Dette burde skrives om til å være render() og forskjellige HTML-pages 😄 (jeg kan fikse det, vil bare skrive det så jeg husker det)

2024-04-30 11:28 UTC, EirikFladby approved these changes

2024-04-30 12:41 UTC, mamikals approved these changes

2024-04-30 13:59 UTC, Triopticon approved these changes
Har ikkje sett så nøye på det, så stoler på at dåke har kontrollen. ;-)

2024-04-30 15:19 UTC, merged